TEAM_TABLE = {
  "Seattle SuperSonics": "sea",
  "Atlanta Hawks": "atl",
  "Boston Celtics": "bos",
  "Brooklyn Nets": "brk",
  "New Jersey Nets": "njn",
  "Charlotte Hornets": "cho",
  "Charlotte Bobcats": "cha",
  "Chicago Bulls": "chi",
  "Cleveland Cavaliers": "cle",
  "Dallas Mavericks": "dal",
  "Denver Nuggets": "den",
  "Detroit Pistons": "det",
  "Golden State Warriors": "gsw",
  "Houston Rockets": "hou",
  "Indiana Pacers": "ind",
  "Los Angeles Clippers": "lac",
  "Los Angeles Lakers": "lal",
  "Memphis Grizzlies": "mem",
  "Portland Trail Blazers": "por",
  "Vancouver Grizzlies": "van",
  "Miami Heat": "mia",
  "Milwaukee Bucks": "mil",
  "Minnesota Timberwolves": "min",
  "New Orleans Hornets": "noh",
  "New Orleans/Oklahoma City Hornets": "nok",
  "New Orleans Pelicans": "nop",
  "New York Knicks": "nyk",
  "Orlando Magic": "orl",
  "Philadelphia 76ers": "phi",
  "Phoenix Suns": "pho",
  "Sacramento Kings": "sac",
  "San Antonio Spurs": "sas",
  "Toronto Raptors": "tor",
  "Utah Jazz": "uta",
  "Washington Wizards": "was",
  "Oklahoma City Thunder": "okc"
}
